repositories:
  - name: goauthentik
    url: https://charts.goauthentik.io/

releases:
  - name: authentik
    namespace: authentik
    chart: goauthentik/authentik
    version: 2023.8.2
    values:
      - authentik:
          log_level: debug
          secret_key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
          error_reporting:
            enabled: true
          postgresql:
            password: "a"
        env:
          AUTHENTIK_BOOTSTRAP_PASSWORD: akadmin
          AUTHENTIK_BOOTSTRAP_TOKEN: aktoken
        ingress:
          enabled: true
          hosts:
            - host: authentik.127-0-0-1.nip.io
              paths:
                - path: "/"
                  pathType: Prefix
        postgresql:
          enabled: true
          postgresqlPassword: "a"
          image:
            tag: 15.4.0-debian-11-r0
        redis:
          enabled: true
