apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: authentik-sandbox
servers: 1
agents: 2
ports:
  - port: 80:80
  - port: 443:443
options:
  k3d:
    wait: true
    timeout: "60s"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
